-- Create table
CREATE TABLE users (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name varchar(40) NOT NULL,
  last_name varchar(40) NOT NULL
);

-- Query the information in the table
SELECT * FROM users;

-- Insert information into table
INSERT INTO users
  (first_name, last_name)
VALUES
  ('Karl', 'Horky'),
  ('Janos', 'Spanyol'),
  ('Nicolas', 'Gadner');
